controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_trick_delete_image:
    path: '/suppression/image/{id}'
    controller: 'App\Controller\TricksController::deleteImage'
    methods: [DELETE]


